name: test
on: [workflow_dispatch]

jobs:
  test:
    name: Test Matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        person: ['Jack', 'Jill']
    steps:
      - name: Say hello to ${{ matrix.person }}
        env:
          NAME: ${{ matrix.person }}
        run: |
          for i in {0..10000}; do
            echo "Hello $NAME"
          done
          exit 1

